### ISSUE TITLE
problems with adding track layers

### ISSUE THREAD

**Issue by HegedusB** [schneebergerlab/plotsr#28]
Hi.
During the testing your great softwer I run into a litle problem. When I try to add tracks layer I get this error message:

Traceback (most recent call last):
  File "/usr/local/bin/plotsr", line 4, in <module>
    __import__('pkg_resources').run_script('plotsr==0.5.4', 'plotsr')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1470, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.8/dist-packages/plotsr-0.5.4-py3.8.egg/EGG-INFO/scripts/plotsr", line 6, in <module>
  File "/usr/local/lib/python3.8/dist-packages/plotsr-0.5.4-py3.8.egg/plotsr/main.py", line 55, in main
  File "/usr/local/lib/python3.8/dist-packages/plotsr-0.5.4-py3.8.egg/plotsr/plotsr.py", line 259, in plotsr
  File "/usr/local/lib/python3.8/dist-packages/plotsr-0.5.4-py3.8.egg/plotsr/func.py", line 1598, in drawtracks
ValueError: max() arg is an empty sequence

The program works fine when I am not asking the tracks layer. Can you help me to finde out the source of the problem?
Thanks!

The commend I used:  
plotsr --sr Am_Bmsyri.out --sr Bm_Cmsyri.out --genomes genomes.txt --tracks tracks.txt --cfg base.cfg --chrord scaffold_order.txt -o output_plot6.png -W 8 -H 8

Tracks:
telomers.bed	Telomser	bw:10000;nc:black;ns:8;nf:Arial;lc:olive;lw:1;bc:palegreen;ba:0.5

Telomers.bed:
scaffold_1	100000	400000
scaffold_2	100000	400000
scaffold_3	100000	400000
scaffold_4	100000	400000
scaffold_5	100000	400000

**Comment by Immortal2333** [comment]
I think you should keep the same with your chromosome ID and "scaffold_1". Maybe it could solve your question.

**Comment by mnshgl0110** [comment]
In addition to checking the chromosome names, please also check whether the filename is correct ("telomers.bed" vs "Telomers.bed")
