### ISSUE TITLE
error while trying to add track

### ISSUE THREAD

**Issue by ylevmirom** [schneebergerlab/plotsr#40]
Hi, great tool. 
I'm trying to add track data using a gff, it worked fine on another segment, 
but now I'm receiving this error: 
```
track - WARNING - Reading GFF file GD_QTL_syri.gff. Overlapping transcripts would be plotted as such without any filtering.
Traceback (most recent call last):
  File "/home/yael/miniconda3/envs/syri_env/bin/plotsr", line 6, in <module>
    main(sys.argv[1:])
  File "/home/yael/miniconda3/envs/syri_env/lib/python3.9/site-packages/plotsr/main.py", line 55, in main
    plotsr(args)
  File "/home/yael/miniconda3/envs/syri_env/lib/python3.9/site-packages/plotsr/plotsr.py", line 257, in plotsr
    tracks = readtrack(TRACKS, chrlengths)
  File "/home/yael/miniconda3/envs/syri_env/lib/python3.9/site-packages/plotsr/func.py", line 732, in readtrack
    t.readdata(chrlengths)
  File "/home/yael/miniconda3/envs/syri_env/lib/python3.9/site-packages/plotsr/func.py", line 702, in readdata
    self._readgff(chrlengths)
  File "/home/yael/miniconda3/envs/syri_env/lib/python3.9/site-packages/plotsr/func.py", line 691, in _readgff
    k = list(model.keys())[0]
AttributeError: 'NoneType' object has no attribute 'keys'
```

my gff looks like this: 
```
chr source type start end score strand phase attributes mRNA
Chr4B UOHWEW2022 mRNA 4092 6166 NA - NA ID=TRIDC4Bv3G05196400;Name=TRIDC4Bv3G05196400;ncbi_loc=.;ncbi_type=NA TRIDC4Bv3G05196400
Chr4B UOHWEW2022 mRNA 165768 167443 NA - NA ID=TRIDC4Bv3G05196500;Name=TRIDC4Bv3G05196500;ncbi_loc=LOC119291282;ncbi_type=mRNA;product=probable protein phosphatase 2C 29 TRIDC4Bv3G05196500
Chr4B UOHWEW2022 mRNA 690044 701457 NA + NA ID=TRIDC4Bv3G05196600;Name=TRIDC4Bv3G05196600;ncbi_loc=LOC119291283;ncbi_type=mRNA;product=casein kinase II subunit alpha-2-like TRIDC4Bv3G05196600
Chr4B UOHWEW2022 mRNA 739602 742424 NA + NA ID=TRIDC4Bv3G05196700;Name=TRIDC4Bv3G05196700;ncbi_loc=LOC119291284;ncbi_type=mRNA;product=54S ribosomal protein L51%2C mitochondrial-like TRIDC4Bv3G05196700
Chr4B UOHWEW2022 mRNA 743540 746453 NA + NA ID=TRIDC4Bv3G05196800;Name=TRIDC4Bv3G05196800;ncbi_loc=LOC119291285;ncbi_type=mRNA;product=uncharacterised protein TRIDC4Bv3G05196800
```

what could be the reason for the error? 

Thanks

Yael

**Comment by mnshgl0110** [comment]
I tried with the attached lines of the GFF and it worked. Could you please share the entire gff file? Also, the reference genome index created using `samtools faidx <REFGENOME>`.

**Comment by ylevmirom** [comment]
attached

**Comment by mnshgl0110** [comment]
sorry, but it is not attached or not visible.

**Comment by ylevmirom** [comment]
dont know why its not visible,
trying again:

**Comment by mnshgl0110** [comment]
I dont think attachments to email are shared by github. You would need to upload it to github's website.

**Comment by ylevmirom** [comment]
it says it doesn't support this file type

**Comment by mnshgl0110** [comment]
change file name to <something.gff.txt> and <something.faidx.txt> that should work

**Comment by ylevmirom** [comment]
[Zavitan2.Chr4B_529730264-538138026.fa.fai.txt](https://github.com/schneebergerlab/plotsr/files/10838867/Zavitan2.Chr4B_529730264-538138026.fa.fai.txt)

**Comment by ylevmirom** [comment]
[GD_QTL_syri.txt](https://github.com/schneebergerlab/plotsr/files/10838877/GD_QTL_syri.txt)

**Comment by mnshgl0110** [comment]
Thanks for sharing. Unfortunately, even these files are working correctly and as such I cannot reproduce the error and don't know why it is not working for you. This error should only happen when the GFF is empty. Please recheck all the paths and files that you are using.

**Comment by ylevmirom** [comment]
OK thanks for your help, 
ill try to figure out over here
