### ISSUE TITLE
plotrs -R doesn't work

### ISSUE THREAD

**Issue by YingLiPUMC** [schneebergerlab/plotsr#45]
Hi，
I tried to draw the syn plot between different subgenomes. I want to use -R to join the adjacent syntenic blocks. But it causes program error. Where did I set it up wrong? Thanks very much. 
By the way, when I remove the -R parameter, it works well. 

Ying

-------------------------But I remove the -R parameter and the program runs fine -h
  -R                    Join adjacent syntenic blocks if they are not interrupted by SRs. Using this would decrease gaps in the
                        visualisation. (default: False)Traceback (most recent call last):
 ------------------------error information
File "/home/xx/anaconda3/envs/syri_env/bin/plotsr", line 6, in <module>
    main(sys.argv[1:])
  File "/home/xx/anaconda3/envs/syri_env/lib/python3.8/site-packages/plotsr/scripts/plotsr.py", line 334, in main
    plotsr(args)
  File "/home/xx/anaconda3/envs/syri_env/lib/python3.8/site-packages/plotsr/scripts/plotsr.py", line 264, in plotsr
    ax, svlabels = pltsv(ax, alignments, chrs, V, chrgrps, chrlengths, indents, S, cfg, ITX, maxl)
  File "/home/xx/anaconda3/envs/syri_env/lib/python3.8/site-packages/plotsr/scripts/func.py", line 1526, in pltsv
    anno = annotodict(row.anno)
  File "/home/xx/anaconda3/envs/syri_env/lib/python3.8/site-packages/plotsr/scripts/func.py", line 1492, in annotodict
    return {a.split(':')[0]: a.split(':')[1] for a in anno.split(';')}
AttributeError: 'float' object has no attribute 'split'

**Comment by mnshgl0110** [comment]
Fixed with https://github.com/schneebergerlab/plotsr/commit/2dff8948a40debccce69ccf106bab5129de75aad

Please reinstall from Github.

**Comment by YingLiPUMC** [comment]
Thank you very much. It works well now.
