### ISSUE TITLE
Problem with the track file

### ISSUE THREAD

**Issue by m-bogaerts** [schneebergerlab/plotsr#50]
I am trying to use a gff file at the track file, however I get the following error:
Traceback (most recent call last):
  File "/home/bogaerts/miniconda3/bin/plotsr", line 4, in <module>
    __import__('pkg_resources').run_script('plotsr==0.5.3', 'plotsr')
  File "/home/bogaerts/miniconda3/lib/python3.9/site-packages/pkg_resources/__init__.py", line 662, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/bogaerts/miniconda3/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1466, in run_script
    exec(script_code, namespace, namespace)
  File "/home/bogaerts/miniconda3/lib/python3.9/site-packages/plotsr-0.5.3-py3.9.egg/EGG-INFO/scripts/plotsr", line 6, in <module>
  File "/home/bogaerts/miniconda3/lib/python3.9/site-packages/plotsr-0.5.3-py3.9.egg/plotsr/main.py", line 55, in main
  File "/home/bogaerts/miniconda3/lib/python3.9/site-packages/plotsr-0.5.3-py3.9.egg/plotsr/plotsr.py", line 257, in plotsr
  File "/home/bogaerts/miniconda3/lib/python3.9/site-packages/plotsr-0.5.3-py3.9.egg/plotsr/func.py", line 723, in readtrack
ValueError: Incomplete line in track file.

File path and name are necessary columns, tags is optional column

However I used the track file as in the example (but in this case with only one line for the gff). Do you have any idea about what could be happening?

Thank you in advance.

**Comment by mnshgl0110** [comment]
Could you please ensure that the columns in the tracks.txt file are separated by tabs and not spaces? Also, remove any empty line. I guess that should resolve this.

**Comment by m-bogaerts** [comment]
Thank you very much/ Actually there were an empty line (sorry for the inconveniences).

However, now I get a new error:
track - WARNING - Reading GFF file Dtol_annotation_genes_polished.gff. Overlapping transcripts would be plotted as such without any filtering.
Traceback (most recent call last):
  File "/home/bogaerts/miniconda3/bin/plotsr", line 4, in <module>
    __import__('pkg_resources').run_script('plotsr==0.5.3', 'plotsr')
  File "/home/bogaerts/miniconda3/lib/python3.9/site-packages/pkg_resources/__init__.py", line 662, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/bogaerts/miniconda3/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1466, in run_script
    exec(script_code, namespace, namespace)
  File "/home/bogaerts/miniconda3/lib/python3.9/site-packages/plotsr-0.5.3-py3.9.egg/EGG-INFO/scripts/plotsr", line 6, in <module>
  File "/home/bogaerts/miniconda3/lib/python3.9/site-packages/plotsr-0.5.3-py3.9.egg/plotsr/main.py", line 55, in main
  File "/home/bogaerts/miniconda3/lib/python3.9/site-packages/plotsr-0.5.3-py3.9.egg/plotsr/plotsr.py", line 257, in plotsr
  File "/home/bogaerts/miniconda3/lib/python3.9/site-packages/plotsr-0.5.3-py3.9.egg/plotsr/func.py", line 729, in readtrack
  File "/home/bogaerts/miniconda3/lib/python3.9/site-packages/plotsr-0.5.3-py3.9.egg/plotsr/func.py", line 699, in readdata
  File "/home/bogaerts/miniconda3/lib/python3.9/site-packages/plotsr-0.5.3-py3.9.egg/plotsr/func.py", line 688, in _readgff
AttributeError: 'NoneType' object has no attribute 'keys'

Thank you in advance.

**Comment by mnshgl0110** [comment]
As the original issue is resolved I will close this. Have started another thread for the second issue.
