### ISSUE TITLE
Error while reading GFF file

### ISSUE THREAD

**Issue by mnshgl0110** [schneebergerlab/plotsr#52]
https://github.com/schneebergerlab/plotsr/issues/50#issuecomment-1584377737

@m-bogaerts

**Comment by mnshgl0110** [comment]
It seems that there is some issue in the formatting of the GFF file. Could you please compare your input GFF with the example GFF. Also, ensure that the transcripts have 'mrna' and 'cds' elements.

**Comment by m-bogaerts** [comment]
Hello again,

Thank you for your response, however y still have the same issue. I checked the example GFF file and I think it is very similar so I am not sure which could be the issue. I leave here some lines of m GFF file:

chr1	Liftoff	exon	15251069	15251169	.	-	.	ID=exon-XR_006747185.1-1;Parent=rna-XR_006747185.1;Dbxref=GeneID:123678035,Genbank:XR_006747185.1;experiment=COORDINATES: polyA evidence [ECO:0006239];gbkey=misc_RNA;gene=LOC123678035;product=protein disulfide-isomerase-like%2C transcript variant X2;transcript_id=XR_006747185.1;extra_copy_number=0
chr1	Liftoff	gene	15253501	15258586	.	-	.	ID=gene-LOC123677994;Dbxref=GeneID:123677994;Name=LOC123677994;gbkey=Gene;gene=LOC123677994;gene_biotype=protein_coding;coverage=1.0;sequence_ID=1.0;valid_ORFs=1;extra_copy_number=0;copy_num_ID=gene-LOC123677994_0
chr1	Liftoff	mRNA	15253501	15258586	.	-	.	ID=rna-XM_045614755.1;Parent=gene-LOC123677994;Dbxref=GeneID:123677994,Genbank:XM_045614755.1;Name=XM_045614755.1;experiment=COORDINATES: polyA evidence [ECO:0006239];gbkey=mRNA;gene=LOC123677994;model_evidence=Supporting evidence includes similarity to: 14 Proteins%2C 4 long SRA reads%2C and 100%25 coverage of the annotated genomic feature by RNAseq alignments%2C including 51 samples with support for all annotated introns;product=protein disulfide-isomerase A5;transcript_id=XM_045614755.1;matches_ref_protein=True;valid_ORF=True;extra_copy_number=0

Thank you in advance.

**Comment by mnshgl0110** [comment]
Difficult to say what are the issues with the GFF. I assume you have ensured that genes have mrna and cds elements. Also, remove any empty lines from the GFF.

**Comment by asan-emirsaleh** [comment]
Hello! I faced the same issue too.
```
Overlapping transcripts would be plotted as such without any filtering.
Traceback (most recent call last):
  File "/home/asan/miniconda3/envs/syri-env/bin/plotsr", line 6, in <module>
    main(sys.argv[1:])
  File "/home/asan/miniconda3/envs/syri-env/lib/python3.8/site-packages/plotsr/scripts/plotsr.py", line 334, in main
    plotsr(args)
  File "/home/asan/miniconda3/envs/syri-env/lib/python3.8/site-packages/plotsr/scripts/plotsr.py", line 276, in plotsr
    tracks = readtrack(TRACKS, chrlengths)
  File "/home/asan/miniconda3/envs/syri-env/lib/python3.8/site-packages/plotsr/scripts/func.py", line 857, in readtrack
    t.readdata(chrlengths)
  File "/home/asan/miniconda3/envs/syri-env/lib/python3.8/site-packages/plotsr/scripts/func.py", line 827, in readdata
    self._readgff(chrlengths)
  File "/home/asan/miniconda3/envs/syri-env/lib/python3.8/site-packages/plotsr/scripts/func.py", line 816, in _readgff
    k = list(model.keys())[0]
AttributeError: 'NoneType' object has no attribute 'keys'
```

There is no empty line in the gff.

**Comment by mnshgl0110** [comment]
@asan-emirsaleh Is your issue resolved?

@novigit Yes, theoretically that is possible. The tricky part is to find time to do that. Nevertheless, it would be great if you could list which feature types would be useful.
