### ISSUE TITLE
A running problem about two genomes with relatively large size differences (~850M vs ~650M)

### ISSUE THREAD

**Issue by Wenwen012345** [schneebergerlab/plotsr#54]
Dear
Hello, the species I am studying is Rhododendron. I have now finished sequencing the genome of my study rhododendron species (Rhododendron bailiense, Rb) in preparation for inter-species covariance analysis.

However, I have found that it seems that because the Rhododendron species I am studying (Rb) has a very large transposon insertion, its genome size appears to be much larger than that of the other reference Rhododendron species in the same genus (and subgenus) (Rhododendron griersonianum, Rg is used here). Their comparative genome sizes are ~850M (Rb) vs ~650M (Rg).

Of course, this is not necessarily a problem, but when I run the syri-plotsr process, the following error is reported when I get to the plotsr step. It seems that this may be caused by a large difference in chromosome length.

```
(syri) w@w:~/w2/HIFI1/juicer/3d-dna-review1-3/syri/Rb_Rg$ plotsr --sr  syri.out --genomes  genomes1.txt -H 8 -W 5
2023-06-18 21:03:21,979 - Plotsr - INFO - Starting
Traceback (most recent call last):
  File "/home/w/miniconda3/envs/syri/bin/plotsr", line 6, in <module>
    main(sys.argv[1:])
  File "/home/w/miniconda3/envs/syri/lib/python3.9/site-packages/plotsr/scripts/plotsr.py", line 334, in main
    plotsr(args)
  File "/home/w/miniconda3/envs/syri/lib/python3.9/site-packages/plotsr/scripts/plotsr.py", line 171, in plotsr
    chrlengths, genomes = validalign2fasta(alignments, args.genomes.name)
  File "/home/w/miniconda3/envs/syri/lib/python3.9/site-packages/plotsr/scripts/func.py", line 1050, in validalign2fasta
    raise ImportError(errmess2.format(c, os.path.basename(genf), als[i][0]))
ImportError: For chromosome ID: Chr10, length in genome fasta: genomes1.txt is less than the maximum coordinate in the structural annotation file: syri.out. Exiting.
```

**Comment by Wenwen012345** [comment]
I tried this process and it should work. Failed twice before because of some negligence....

@mnshgl0110
