### ISSUE TITLE
ValueError: tt is not a valid tag

### ISSUE THREAD

**Issue by hushaoqiang** [schneebergerlab/plotsr#66]
Hello, I am running the example file and received this error. May I know how to resolve this issue.
Thanks.

$ /home/hsqhsq/miniconda3/envs/syri_env/bin/plotsr --sr col_lersyri.filtered.out --sr ler_cvisyri.filtered.out --sr cvi_erisyri.filtered.out        --genomes genomes.txt --tracks tracks.txt --cfg base.cfg -o output_plot.png -S 0.5 -W 7 -H 10 -f 8

track - WARNING - Reading GFF file TAIR10_GFF3_genes.gff. Overlapping transcripts would be plotted as such without any filtering.
Traceback (most recent call last):
  File "/home/hsqhsq/miniconda3/envs/syri_env/bin/plotsr", line 6, in <module>
    main(sys.argv[1:])
  File "/home/hsqhsq/miniconda3/envs/syri_env/lib/python3.9/site-packages/plotsr/main.py", line 55, in main
    plotsr(args)
  File "/home/hsqhsq/miniconda3/envs/syri_env/lib/python3.9/site-packages/plotsr/plotsr.py", line 257, in plotsr
    tracks = readtrack(TRACKS, chrlengths)
  File "/home/hsqhsq/miniconda3/envs/syri_env/lib/python3.9/site-packages/plotsr/func.py", line 730, in readtrack
    t.addtags(line[2])
  File "/home/hsqhsq/miniconda3/envs/syri_env/lib/python3.9/site-packages/plotsr/func.py", line 496, in addtags
    raise ValueError("{} is not a valid tag".format(n))
ValueError: tt is not a valid tag

**Comment by mnshgl0110** [comment]
Are you using latest version of plotsr?

**Comment by hushaoqiang** [comment]
Hello, I am not using the latest version.
I found that after removing the tt tag from the track.txt file, I can successfully run it.
Thank you.
