### ISSUE TITLE
ValueError when running plotsr function

### ISSUE THREAD

**Issue by ngorringe** [schneebergerlab/plotsr#68]
Hi there,

I keep getting the same error when running the plotsr function that I cannot seem to fix. All other steps leading up to the plotsr function work fine. 

My command is:
plotsr --sr A_Bsyri.out \
    --sr B_Csyri.out \
    --genomes genomes.txt \
    --tracks tracks.txt \
    --cfg base.cfg \
    -o output_plot.png

The error is:
Traceback (most recent call last):
  File "/path/miniconda3/bin/plotsr", line 6, in <module>
    main(sys.argv[1:])
  File "/path/miniconda3/lib/python3.9/site-packages/plotsr/main.py", line 55, in main
    plotsr(args)
  File "/path/miniconda3/lib/python3.9/site-packages/plotsr/plotsr.py", line 152, in plotsr
    chrlengths, genomes = validalign2fasta(alignments, args.genomes.name)
  File "/path/miniconda3/lib/python3.9/site-packages/plotsr/func.py", line 872, in validalign2fasta
    gen.addtags(line[2])
  File "/path/miniconda3/lib/python3.9/site-packages/plotsr/func.py", line 760, in addtags
    n, v = i.split(":")
ValueError: too many values to unpack (expected 2)

Thank you in advance! 

Best,
Nicola

**Comment by ngorringe** [comment]
All solved, thank you! I needed to change the file names for some of the genomes
