### ISSUE TITLE
ImportError: For chromosome ID: Hic3, length in genome fasta: genome.txt is less than the maximum coordinate in the structural annotation file: syri.out. Exiting.

### ISSUE THREAD

**Issue by wangguiqian** [schneebergerlab/plotsr#70]
This my genome.txt file,but when I run plotsr ,then bollow 
#file   name    tags
1C32_ragtag.fa  1C32    lw:1.5
GCA_000400815.2_ragtag.fa       GCA_000400815.2 lw:1.5
GCA_000952015.1_ragtag.fa       GCA_000952015.1 lw:1.5
GCA_018140845.1_ragtag.fa       GCA_018140845.1 lw:1.5
GCA_018440705.1_ragtag.fa       GCA_018440705.1 lw:1.5

/public/home/yqming/miniconda3/envs/syri/bin/plotsr:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
   __import__('pkg_resources').run_script('plotsr==1.1.2', 'plotsr')
2023-11-22 12:30:26,241 - Plotsr - INFO - Starting
Traceback (most recent call last):
  File "/public/home/yqming/miniconda3/envs/syri/bin/plotsr", line 4, in <module>
    __import__('pkg_resources').run_script('plotsr==1.1.2', 'plotsr')
  File "/public/home/yqming/miniconda3/envs/syri/lib/python3.9/site-packages/pkg_resources/__init__.py", line 722, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/public/home/yqming/miniconda3/envs/syri/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1572, in run_script 
     exec(script_code, namespace, namespace)
  File "/public/home/yqming/miniconda3/envs/syri/lib/python3.9/site-packages/plotsr-1.1.2-py3.9.egg/EGG-INFO/scripts/plotsr", line 6, in <module>
  File "/public/home/yqming/miniconda3/envs/syri/lib/python3.9/site-packages/plotsr-1.1.2-py3.9.egg/plotsr/scripts/plotsr.py", line 334, in main
  File "/public/home/yqming/miniconda3/envs/syri/lib/python3.9/site-packages/plotsr-1.1.2-py3.9.egg/plotsr/scripts/plotsr.py", line 171, in plotsr
  File "/public/home/yqming/miniconda3/envs/syri/lib/python3.9/site-packages/plotsr-1.1.2-py3.9.egg/plotsr/scripts/func.py", line 1050, in validalign2fasta
ImportError: For chromosome ID: Hic3, length in genome fasta: genome.txt is less than the maximum coordinate in the structural annotation file: syri.out. Exiting.

why is Hic3 very too long ? How to solve this strange problem?

**Comment by mnshgl0110** [comment]
The order of genomes in genomes.txt need to match the order in which the syri output is provided. From the README:
```
NOTE: It is required that the order of the genomes is the same as the order in which genomes are compared. For example, if the first genome annotation file uses A as a reference and B as query, and the second genome annotation file uses B as a reference and C as query, then the genomes.txt file should list the genomes in the order A, B, C.
```
Please check that your input files and genome order are consistent.
