### ISSUE TITLE
--nosyn didnt work

### ISSUE THREAD

**Issue by jurin0811** [schneebergerlab/plotsr#76]
Hi,
I had a problem with plotsr that couldn't generate an image when I added "--nosyn". 
my code :plotsr --sr B73BY815.out --sr BY815mo17.out --genome genomes.txt --nosyn -s 40000 -W 10 -H 7 -S 0.7 -o B73BY815MP17_syri.png
Traceback (most recent call last):
  File "/share/home/cau_zhul/.conda/envs/svcalling/bin/plotsr", line 6, in <module>
    main(sys.argv[1:])
  File "/share/home/cau_zhul/.conda/envs/svcalling/lib/python3.9/site-packages/plotsr/scripts/plotsr.py", line 334, in main
    plotsr(args)
  File "/share/home/cau_zhul/.conda/envs/svcalling/lib/python3.9/site-packages/plotsr/scripts/plotsr.py", line 245, in plotsr
    ax = drawax(ax, chrgrps, chrlengths, V, S, cfg, ITX, minl=minl, maxl=maxl, chrname=CHRNAME)
  File "/share/home/cau_zhul/.conda/envs/svcalling/lib/python3.9/site-packages/plotsr/scripts/func.py", line 1372, in drawax
    maxl = np.max([chrlengths[i][1][c[i]] for c in chrgrps.values() for i in range(len(c))])
  File "/share/home/cau_zhul/.conda/envs/svcalling/lib/python3.9/site-packages/plotsr/scripts/func.py", line 1372, in <listcomp>
    maxl = np.max([chrlengths[i][1][c[i]] for c in chrgrps.values() for i in range(len(c))])
KeyError: 'chr10'
The program works fine when I remove "--nosyn", my plotsr version is 1.1.1. can you help me ?Thanks!

**Comment by mnshgl0110** [comment]
Hi @jurin0811 . The `--nosyn` parameters seems to work fine on the test data, so as such I cannot replicate the error.

Nevertheless, I have made a change that might fix this issue and pushed it to the main branch. Can you please re-install plotsr (from github) and check if this solves the issue.
