### ISSUE TITLE
Is there a way to compare mutiple assemblies to a reference genome?

### ISSUE THREAD

**Issue by mariaelf97** [schneebergerlab/plotsr#80]
Hello,

Thanks for the great tool
I was wondering if there is a way to compare multiple assemblies in one figure instead of having to generate multiple ones?
I have tried 
`plotsr --sr sample1/syri.out --sr sample2/syri.out --genomes genomes.txt -o output_plot.png`

I also provide the genomes.txt file as specified along with the reference and whole genome of both samples.
`
#file	name	tags
ref.fasta	ref	lw:1.5
sample1.fna	sample1	lw:1.5
sample2.fna	sample2	lw:1.5
'
But it gives me a key error, am I doing this the right way?

**Comment by mnshgl0110** [comment]
Have you checked the description provided [here](https://github.com/schneebergerlab/plotsr?tab=readme-ov-file#inputs-requirements)?

**Comment by mariaelf97** [comment]
hello,

Thanks for your reply.
I have tried 
`plotsr --sr ../GCA_014899485.1/syri.out --sr ../GCA_014899485.1/syri.out --sr ../GCA_014899485.1/syri.out --genomes genomes.txt -o output.png
`
genomes.txt file
`#file	name	tags
/home/mahmadi/tb_seqs/H37Rv/H37Rv.fasta	H37Rv	lw:1.5
/home/mahmadi/tb_seqs/assemblies/long_read_assemblies/pacbio-RSII/GCA_014899485.1/GCA_014899485.1.fna	GCA_014899485.1	lw:1.5
/home/mahmadi/tb_seqs/assemblies/long_read_assemblies/pacbio-RSII/GCA_014899425.1/GCA_014899485.1.fna	GCA_014899425.1	lw:1.5
/home/mahmadi/tb_seqs/assemblies/long_read_assemblies/pacbio-RSII/GCA_014884625.1/GCA_014899485.1.fna	GCA_014899485.1	lw:1.5`

an example of syri.out file
`H37Rv   1       4411532 -       -       CP041802.1      1       4410647 SYN1    -       SYN     -
H37Rv   1       104766  -       -       CP041802.1      1       104811  SYNAL1  SYN1    SYNAL   -
H37Rv   1977    1977    A       G       CP041802.1      1977    1977    SNP17   SYN1    SNP     -
H37Rv   2532    2532    T       C       CP041802.1      2532    2532    SNP18   SYN1    SNP     -
H37Rv   4013    4013    T       C       CP041802.1      4013    4013    SNP19   SYN1    SNP     -
H37Rv   5401    5401    C       T       CP041802.1      5401    5401    SNP20   SYN1    SNP     -
H37Rv   5627    5627    G       T       CP041802.1      5627    5627    SNP21   SYN1    SNP     -
H37Rv   6112    6112    G       C       CP041802.1      6112    6112    SNP22   SYN1    SNP     -
H37Rv   7362    7362    G       C       CP041802.1      7362    7362    SNP23   SYN1    SNP     -
H37Rv   7585    7585    G       C       CP041802.1      7585    7585    SNP24   SYN1    SNP     -
H37Rv   8452    8452    C       T       CP041802.1      8452    8452    SNP25   SYN1    SNP     -
H37Rv   9143    9143    T       C       CP041802.1      9143    9143    SNP26   SYN1    SNP     -
H37Rv   9304    9304    G       A       CP041802.1      9304    9304    SNP27   SYN1    SNP     -
H37Rv   11879   11879   A       G       CP041802.1      11879   11879   SNP28   SYN1    SNP     -
H37Rv   13100   13100   C       T       CP041802.1      13100   13100   SNP29   SYN1    SNP     -
H37Rv   13275   13275   T       C       CP041802.1      13275   13275   SNP30   SYN1    SNP     -
`
but this is the error I get:
` File "/storage/mahmadi/mambaforge/envs/syri/bin/plotsr", line 6, in <module>
    main(sys.argv[1:])
  File "/storage/mahmadi/mambaforge/envs/syri/lib/python3.10/site-packages/plotsr/scripts/plotsr.py", line 334, in main
    plotsr(args)
  File "/storage/mahmadi/mambaforge/envs/syri/lib/python3.10/site-packages/plotsr/scripts/plotsr.py", line 161, in plotsr
    n = chrids[i][1][cur]
KeyError: 'CP041802.1'`


I am not including annotations so I did not define markers and tracks as an input.

**Comment by mnshgl0110** [comment]
That commands did you use to generate the `../GCA_014899485.1/syri.out`, `../GCA_014899485.1/syri.out`, and `../GCA_014899485.1/syri.out` files?

**Comment by mariaelf97** [comment]
I used 
`syri -c aln.sam -r /home/mahmadi/tb_seqs/H37Rv/H37Rv.fasta  -q /home/mahmadi/tb_seqs/assemblies/long_read_assemblies/pacbio-RSII/GCA_014899485.1/GCA_014899485.1.fna -k -F S`

**Comment by mnshgl0110** [comment]
I just noticed that in your plotsr command, you have the same syri.out file three times.

**Comment by mariaelf97** [comment]
Sorry I copied the wrong command
The genomes.txt file
```
#file	name	tags
/home/mahmadi/tb_seqs/H37Rv/H37Rv.fasta	H37Rv	lw:1.5
/home/mahmadi/tb_seqs/assemblies/long_read_assemblies/pacbio-RSII/GCA_014899485.1/GCA_014899485.1.fna	GCA_014899485.1	lw:1.5
/home/mahmadi/tb_seqs/assemblies/long_read_assemblies/pacbio-RSII/GCA_014899425.1/GCA_014899425.1.fna	GCA_014899425.1	lw:1.5
/home/mahmadi/tb_seqs/assemblies/long_read_assemblies/pacbio-RSII/GCA_014884625.1/GCA_014884625.1.fna	GCA_014884625.1	lw:1.5
```
the command 
`plotsr --sr ../GCA_014899485.1/syri.out --sr ../GCA_014899425.1/syri.out --sr ../GCA_014884625.1/syri.out --genomes genomes.txt -o output.png`

I get the same error as before
```
Traceback (most recent call last):
  File "/storage/mahmadi/mambaforge/envs/syri/bin/plotsr", line 6, in <module>
    main(sys.argv[1:])
  File "/storage/mahmadi/mambaforge/envs/syri/lib/python3.10/site-packages/plotsr/scripts/plotsr.py", line 334, in main
    plotsr(args)
  File "/storage/mahmadi/mambaforge/envs/syri/lib/python3.10/site-packages/plotsr/scripts/plotsr.py", line 161, in plotsr
    n = chrids[i][1][cur]
KeyError: 'CP041802.1'
```

**Comment by mariaelf97** [comment]
oh that makes it difficult to compare everything against a reference genome but thank you for explaining it.
