### ISSUE TITLE
parameter error in base.cfg

### ISSUE THREAD

**Issue by yanyew** [schneebergerlab/plotsr#89]
Thanks for developing such great tool!
I tried the `base.cfg` in the example:
`## COLOURS and transparency for alignments (syntenic, inverted, translocated, and duplicated)
syncol:#CCCCCC
invcol:#FFA500
tracol:#9ACD32
dupcol:#00BBFF
synlwd:0                ## Line width for syntenic annotations
invlwd:0.1              ## Line width for inversions
tralwd:0.1              ## Line width for translocations
duplwd:0.1              ## Line width for duplications
alpha:0.8

## Margins and dimensions:
chrmar:0.1              ## Adjusts the gap between chromosomes and tracks. Higher values leads to more gap
exmar:0.1               ## Extra margin at the top and bottom of plot area
marginchr:0.1           ## Margin between adjacent chromosomes when using --itx

## Legend
legend:T                ## To plot legend use T, use F to not plot legend
genlegcol:-1            ## Number of columns for genome legend, set -1 for automatic setup
bbox:0,1.01,0.5,0.3		## [Left edge, bottom edge, width, height]
bbox_v:0,1.1,0.5,0.3	## For vertical chromosomes (using -v option)
bboxmar:0.5             ## Margin between genome and annotation legends

## Tracks
norm:T                  ## For each chromosome, independently normalise the y-axis of tracks. Use T for normalising independently, and F to normalise based on max value across all chromosomes

## Axis
maxl:-1                 ## Manually set maximum chromosome position. Use `-1` for automatic selection. Does not work with --itx
genname:T               ## Write genome names adjacent to the chromosome (T) or not (F)`

but got the error message as follow:
`readbasecfg - ERROR - synlwd is not a valid config parameter. Using default value.
readbasecfg - ERROR - invlwd is not a valid config parameter. Using default value.
readbasecfg - ERROR - tralwd is not a valid config parameter. Using default value.
readbasecfg - ERROR - duplwd is not a valid config parameter. Using default value.
readbasecfg - ERROR - norm is not a valid config parameter. Using default value.
readbasecfg - ERROR - maxl is not a valid config parameter. Using default value.
readbasecfg - ERROR - genname is not a valid config parameter. Using default value.`

Have these config parameters been discarded？

**Comment by yuyingrong** [comment]
Hi,

Thanks for your question! These contig parameters in the example `base.cfg` file are no longer supported in the current conda release. However, these errors should not prevent the plot from being generated. We are currently working on updating the example files for the next release. Would you like to adjust a certain parameter or do you have issues with generating the plot? 

Cheers,
Yuying

**Comment by HLHsieh** [comment]
Hi Yuying

I also encountered similar issue. I was trying on example data you provided. I ran `plotsr --sr col_lersyri.filtered.out --sr ler_cvisyri.filtered.out --sr cvi_erisyri.filtered.out --genomes genomes.txt --tracks tracks.txt --markers markers.bed --cfg base.cfg -o output_plot.png -S 0.5 -W 7 -H 10 -f 8`


I encountered the error and no plot was generated.
```
2025-01-28 03:36:58,123 - Plotsr - INFO - Starting
readbasecfg - ERROR - synlwd is not a valid config parameter. Using default value.
readbasecfg - ERROR - invlwd is not a valid config parameter. Using default value.
readbasecfg - ERROR - tralwd is not a valid config parameter. Using default value.
readbasecfg - ERROR - duplwd is not a valid config parameter. Using default value.
readbasecfg - ERROR - norm is not a valid config parameter. Using default value.
readbasecfg - ERROR - maxl is not a valid config parameter. Using default value.
readbasecfg - ERROR - genname is not a valid config parameter. Using default value.
Traceback (most recent call last):
  File "/nfs/turbo/umms-kinfai/hsinlun/miniconda3/envs/syri_env/bin/plotsr", line 6, in <module>
    main(sys.argv[1:])
  File "/nfs/turbo/umms-kinfai/hsinlun/miniconda3/envs/syri_env/lib/python3.10/site-packages/plotsr/scripts/plotsr.py", line 334, in main
    plotsr(args)
  File "/nfs/turbo/umms-kinfai/hsinlun/miniconda3/envs/syri_env/lib/python3.10/site-packages/plotsr/scripts/plotsr.py", line 272, in plotsr
    ax = drawmarkers(ax, B, V, chrlengths, indents, chrs, chrgrps, S, cfg, ITX, minl=minl, maxl=maxl)
  File "/nfs/turbo/umms-kinfai/hsinlun/miniconda3/envs/syri_env/lib/python3.10/site-packages/plotsr/scripts/func.py", line 1696, in drawmarkers
    mdata = readannobed(b, v, chrlengths)
  File "/nfs/turbo/umms-kinfai/hsinlun/miniconda3/envs/syri_env/lib/python3.10/site-packages/plotsr/scripts/func.py", line 418, in readannobed
    anno.addtags(line[4])
  File "/nfs/turbo/umms-kinfai/hsinlun/miniconda3/envs/syri_env/lib/python3.10/site-packages/plotsr/scripts/func.py", line 384, in addtags
    raise ValueError("{} is not a valid tag".format(n))
ValueError: mz is not a valid tag
```

Any suggestions would be appreciated.

Best,
Hsin

**Comment by mnshgl0110** [comment]
Hi @HLHsieh , this is the same error. I would recommend that a) either you try installing the github version of the plotsr, or b) remove these tags from the base.cfg file. Please check [these older files](https://github.com/schneebergerlab/plotsr/tree/50fbc6bc48b9038b4235471d32d12f3dd6e6ef57/example) for tags accepted by the conda version.

**Comment by HLHsieh** [comment]
Thank you for your quick response! I tried installing the GitHub version of plotsr, and it works perfectly.
